# -*- coding: utf-8 -*-
"""MINI PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nynPtxmbF53CxfAFXpUVP_OXOxbX-0GE
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
import numpy as np

# 1. Own Dataset Create Pannudhal
# 1000 samples, 4 features ulla dummy data
X_train = np.random.rand(1000, 4)
# Target: Feature-in kootuthogai > 2 endraal 1, illaiyenil 0
y_train = (np.sum(X_train, axis=1) > 2).astype(int)

# 2. Build a Sequential Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)), # Input Layer
    Dense(4, activation='relu'),                  # Hidden Layer
    Dense(1, activation='sigmoid')                # Output Layer (Binary Classification)
])

# 3. Compile with Loss and Optimizer
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 4. Train the Model
print("--- Training Start ---")
model.fit(X_train, y_train, epochs=10, batch_size=10, verbose=0)

# 5. Evaluate the Model
loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
print(f"\nEvaluation Results: Accuracy: {accuracy*100:.2f}%, Loss: {loss:.4f}")

# 6. Save the Model
model.save('my_model.keras')
print("\nModel 'my_model.keras' endra peyaril save seiyappattadhu.")

# 7. Test the Saved Model
loaded_model = load_model('my_model.keras')
test_data = np.array([[0.8, 0.9, 0.7, 0.6]]) # High values, result 1 vara vaaippu undu
prediction = loaded_model.predict(test_data)
print(f"Test Prediction for {test_data}: {prediction[0][0]:.4f}")